[package]
name = "cuicui_layout_bevy_sprite"
description = "Integration with bevy_sprite for cuicui_layout"
categories = ["game-development", "gui"]
keywords = ["bevy", "layout", "ui", "sprite", "2d"]
readme = "README.md"
version = "0.8.1"
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[features]
default = ["sprite_text", "reflect"]
reflect = ["cuicui_layout/reflect"]
sprite_text = []

[dependencies]
bevy_mod_sysfail.workspace = true
cuicui_dsl.workspace = true
cuicui_layout.workspace = true
bevy = { version = "0.11", default-features = false, features = ["bevy_sprite", "bevy_text", "bevy_core_pipeline", "bevy_asset", "bevy_render"] }
