[package]
name = "cuicui_layout_bevy_sprite"
description = "Integration with bevy_sprite for cuicui_layout"
categories = ["game-development", "gui"]
keywords = ["bevy", "layout", "ui", "sprite", "2d"]
readme.workspace = true
edition.workspace = true
version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
bevy_mod_sysfail.workspace = true
bevy = { version = "0.10", default-features = false, features = ["bevy_sprite", "bevy_core_pipeline", "bevy_render"] }
cuicui_layout.workspace = true
