[workspace]
resolver = "2"
exclude = ["assets/", "design_docs/"]
members = [
  "examples/*",
  "layout",
  "sprite",
  "ui",
  "dsl",
]

[workspace.package]
edition = "2021"
version = "0.3.0"
authors = ["Nicola Papale"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/nicopap/cuicui_layout"

[workspace.dependencies]
ahash = "0.8"
anyhow = "1"
bevy_mod_sysfail = "3"
# bevy-inspector-egui = "0.18.3"
thiserror = "1"
# winnow = "0.4.9"

cuicui_layout = { version = "0.3.0", path = "./layout" }
cuicui_layout_bevy_sprite = { version = "0.3.0", path = "./sprite" }
cuicui_layout_bevy_ui = { version = "0.3.0", path = "./ui" }
cuicui_dsl = { version = "0.3.0", path = "./dsl" }
