[workspace]
resolver = "2"
members = [
  "sprite",
  # "ui",
  "examples/*",
]
excludes = []

[workspace.package]
edition = "2021"
version = "0.1.0"
authors = ["Nicola Papale"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/nicopap/cuicui_layout"

[workspace.dependencies]
cuicui_layout = { version = "0.1.0", path = "./layout" }
cuicui_layout_bevy_sprite = { version = "0.1.0", path = "./sprite" }

