[workspace]
resolver = "2"
exclude = ["assets/", "design_docs/"]
members = [
  "sprite",
  "ui",
  "layout",
  # "spec",
  "examples/*",
]

[workspace.package]
edition = "2021"
version = "0.1.0"
authors = ["Nicola Papale"]
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/nicopap/cuicui_layout"

[workspace.dependencies]
ahash = "0.8"
anyhow = "1"
bevy_mod_sysfail = "2"
bevy-inspector-egui = "0.18.3"
thiserror = "1"

cuicui_layout = { path = "./layout" }
cuicui_layout_bevy_sprite = { path = "./sprite" }
cuicui_layout_bevy_ui = { path = "./ui" }
