[workspace]
resolver = "2"
exclude = ["assets/"]
members = [
  "examples/*",
  "layout",
  "sprite",
  "ui",
  "dsl",
]

[workspace.package]
edition = "2021"
authors = ["Nicola Papale"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/nicopap/cuicui_layout"

[workspace.dependencies]
anyhow = "1"
bevy_mod_sysfail = "3"
bevy-inspector-egui = "0.19"
enumset = "1.1"
thiserror = "1"
# winnow = "0.4.9"

cuicui_layout = { version = "0.8.0", path = "./layout", default-features = false }
cuicui_layout_bevy_sprite = { version = "0.8.0", path = "./sprite", default-features = false }
cuicui_layout_bevy_ui = { version = "0.8.0", path = "./ui" }
cuicui_dsl = { version = "0.8.1", path = "./dsl" }
cuicui = { version = "0.8.0", path = "./cuicui" }

[workspace.metadata.release]
dependent-version = "upgrade"
