[package]
name = "cuicui_layout"
authors = ["Nicola Papale"]
description = "A layout algorithm made to be understood by humans"
license = "MIT OR Apache-2.0"
readme = "README.md"
keywords = ["bevy", "layout", "ui"]
categories = ["game-development", "gui"]
repository = "https://github.com/nicopap/cuicui"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
thiserror = "1"
bevy_mod_sysfail = "2"
bevy = { version = "0.10", default-features = false }

[dev-dependencies]
bevy-inspector-egui = "0.18.3"
bevy = { version = "0.10", features = ["png", "x11", "bevy_asset", "bevy_render" ] }
