[book]
title = "The Cuicui Book"
authors = ["Nicola Papale"]
language = "en"
multilingual = false
description = "The user guide and reference of the cuicui framework"
src = "."

[output.html]
default-theme = "rust"
curly-quotes = true
additional-css = ["custom.css"]