[package]
name = "cuicui_layout"
description = "A layout algorithm for bevy and made to be understood by humans"
categories = ["game-development", "gui"]
keywords = ["bevy", "layout", "ui"]
readme = "../README.md"
edition.workspace = true
version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[features]
default = ["reflect"]
reflect = []

[dependencies]
anyhow = "1"
thiserror = "1"
bevy_mod_sysfail.workspace = true
bevy = { version = "0.11", default-features = false }
cuicui_dsl.workspace = true

[package.metadata.release]
pre-release-replacements = [
  {file="../README.md", search="cuicui_layout = .*", replace="cuicui_layout = \"{{version}}\""},
  {file="../README.md", search="cuicui_layout_bevy_ui = .*", replace="cuicui_layout_bevy_ui = \"{{version}}\""},
  {file="../README.md", search="\\| 0.11 \\| 0.4.0 \\|", replace="| 0.11 | {{version}} |"},
]
