[package]
name = "cuicui_layout"
description = "A layout algorithm for bevy and made to be understood by humans"
categories = ["game-development", "gui"]
keywords = ["bevy", "layout", "ui"]
readme = "../README.md"
version = "0.7.2"
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[features]
default = ["reflect"]
debug = ["bevy/bevy_gizmos", "bevy/bevy_render", "bevy/bevy_core_pipeline"]
reflect = []

[dependencies]
anyhow.workspace = true
thiserror.workspace = true
bevy_mod_sysfail.workspace = true
bevy = { version = "0.11", default-features = false }
cuicui_dsl.workspace = true
enumset.workspace = true

[package.metadata.release]
pre-release-replacements = [
  {file="../README.md", search="cuicui_layout = .*", replace="cuicui_layout = \"{{version}}\""},
  {file="../README.md", search="\\| 0.11 \\| [0-9.]* \\|", replace="| 0.11 | {{version}} |"},
]

[package.metadata.docs.rs]
features = ["debug"]
