[package]
name = "cuicui_layout_bevy_ui"
description = "Integration with bevy_ui for cuicui_layout"
categories = ["game-development", "gui"]
keywords = ["bevy", "layout", "ui"]
readme = "README.md"
edition.workspace = true
version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
bevy_mod_sysfail.workspace = true
bevy = { version = "0.11", default-features = false, features = ["bevy_ui", "bevy_text", "bevy_core_pipeline", "bevy_asset", "bevy_render"] }
cuicui_dsl.workspace = true
cuicui_layout.workspace = true
