name: Continous Integration

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLORS: always

jobs:
  clippy_check:
    name: Check clippy lints
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy,rustfmt
      - name: Install alsa and udev
        run: sudo apt-get update; sudo apt-get install --no-install-recommends libasound2-dev libudev-dev
      - name: Check clippy
        run: cargo clippy --workspace -- --deny clippy::pedantic --deny clippy::nursery
      - name: Check documentation
        run: cargo doc --workspace --no-deps
      - name: Run tests
        run: cargo test
      - name: Check formatting
        run: cargo fmt --all -- --check
